# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_V1.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1045, 999)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 40, 961, 781))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.textBox_2 = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textBox_2.setObjectName("textBox_2")
        self.verticalLayout_4.addWidget(self.textBox_2)
        self.browseButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.browseButton_2.setFont(font)
        self.browseButton_2.setObjectName("browseButton_2")
        self.verticalLayout_4.addWidget(self.browseButton_2)
        self.gridLayout.addLayout(self.verticalLayout_4, 2, 4, 1, 1)
        self.line_35 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_35.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_35.setObjectName("line_35")
        self.gridLayout.addWidget(self.line_35, 10, 5, 1, 1)
        self.line_56 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_56.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_56.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_56.setObjectName("line_56")
        self.gridLayout.addWidget(self.line_56, 7, 3, 1, 1)
        self.line_31 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_31.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.gridLayout.addWidget(self.line_31, 4, 5, 1, 1)
        self.line_50 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_50.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_50.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_50.setObjectName("line_50")
        self.gridLayout.addWidget(self.line_50, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 7, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 3, 7, 1, 1)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 2, 1, 1)
        self.line_17 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.gridLayout.addWidget(self.line_17, 12, 2, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 6, 4, 1, 1)
        self.line_20 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.gridLayout.addWidget(self.line_20, 12, 7, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout.addWidget(self.line_10, 6, 7, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 3, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 13, 0, 1, 1)
        self.line_13 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout.addWidget(self.line_13, 9, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 10, 0, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout.addWidget(self.line_11, 9, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.line_14 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout.addWidget(self.line_14, 9, 4, 1, 1)
        self.line_15 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout.addWidget(self.line_15, 9, 7, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 3, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 3, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 4, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 6, 3, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 6, 2, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout.addWidget(self.line_12, 9, 2, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 6, 0, 1, 1)
        self.line_19 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.gridLayout.addWidget(self.line_19, 12, 4, 1, 1)
        self.line_16 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.gridLayout.addWidget(self.line_16, 12, 0, 1, 1)
        self.line_18 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.gridLayout.addWidget(self.line_18, 12, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.line_21 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.gridLayout.addWidget(self.line_21, 1, 2, 1, 1)
        self.line_22 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.gridLayout.addWidget(self.line_22, 1, 4, 1, 1)
        self.line_23 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.gridLayout.addWidget(self.line_23, 1, 7, 1, 1)
        self.line_24 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.gridLayout.addWidget(self.line_24, 1, 0, 1, 1)
        self.line_49 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_49.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_49.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_49.setObjectName("line_49")
        self.gridLayout.addWidget(self.line_49, 0, 3, 1, 1)
        self.line_41 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_41.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_41.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_41.setObjectName("line_41")
        self.gridLayout.addWidget(self.line_41, 4, 1, 1, 1)
        self.line_33 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_33.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.gridLayout.addWidget(self.line_33, 7, 5, 1, 1)
        self.line_39 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_39.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_39.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_39.setObjectName("line_39")
        self.gridLayout.addWidget(self.line_39, 2, 1, 1, 1)
        self.line_51 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_51.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_51.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_51.setObjectName("line_51")
        self.gridLayout.addWidget(self.line_51, 0, 5, 1, 1)
        self.line_37 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_37.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_37.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_37.setObjectName("line_37")
        self.gridLayout.addWidget(self.line_37, 13, 5, 1, 1)
        self.line_29 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_29.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.gridLayout.addWidget(self.line_29, 2, 5, 1, 1)
        self.line_45 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_45.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_45.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_45.setObjectName("line_45")
        self.gridLayout.addWidget(self.line_45, 10, 1, 1, 1)
        self.line_47 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_47.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_47.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_47.setObjectName("line_47")
        self.gridLayout.addWidget(self.line_47, 13, 1, 1, 1)
        self.line_54 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_54.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_54.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_54.setObjectName("line_54")
        self.gridLayout.addWidget(self.line_54, 4, 3, 1, 1)
        self.line_43 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_43.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_43.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_43.setObjectName("line_43")
        self.gridLayout.addWidget(self.line_43, 7, 1, 1, 1)
        self.line_52 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_52.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_52.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_52.setObjectName("line_52")
        self.gridLayout.addWidget(self.line_52, 2, 3, 1, 1)
        self.line_58 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_58.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_58.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_58.setObjectName("line_58")
        self.gridLayout.addWidget(self.line_58, 13, 3, 1, 1)
        self.line_60 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_60.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_60.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_60.setObjectName("line_60")
        self.gridLayout.addWidget(self.line_60, 10, 3, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textBox_1 = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textBox_1.setObjectName("textBox_1")
        self.verticalLayout_3.addWidget(self.textBox_1)
        self.browseButton_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.browseButton_1.setFont(font)
        self.browseButton_1.setObjectName("browseButton_1")
        self.verticalLayout_3.addWidget(self.browseButton_1)
        self.gridLayout.addLayout(self.verticalLayout_3, 2, 2, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.startNM_2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.startNM_2.setDecimals(0)
        self.startNM_2.setMinimum(360.0)
        self.startNM_2.setMaximum(1800.0)
        self.startNM_2.setObjectName("startNM_2")
        self.horizontalLayout_6.addWidget(self.startNM_2)
        self.line_62 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_62.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_62.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_62.setObjectName("line_62")
        self.horizontalLayout_6.addWidget(self.line_62)
        self.stopNM_2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.stopNM_2.setDecimals(0)
        self.stopNM_2.setMinimum(360.0)
        self.stopNM_2.setMaximum(1800.0)
        self.stopNM_2.setProperty("value", 1800.0)
        self.stopNM_2.setObjectName("stopNM_2")
        self.horizontalLayout_6.addWidget(self.stopNM_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.line_65 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_65.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_65.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_65.setObjectName("line_65")
        self.verticalLayout_5.addWidget(self.line_65)
        self.calculateButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.calculateButton_2.setFont(font)
        self.calculateButton_2.setObjectName("calculateButton_2")
        self.verticalLayout_5.addWidget(self.calculateButton_2)
        self.exportButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exportButton_2.setFont(font)
        self.exportButton_2.setObjectName("exportButton_2")
        self.verticalLayout_5.addWidget(self.exportButton_2)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 4, 7, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.textBox_4 = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textBox_4.setObjectName("textBox_4")
        self.verticalLayout_7.addWidget(self.textBox_4)
        self.browseButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.browseButton_4.setFont(font)
        self.browseButton_4.setObjectName("browseButton_4")
        self.verticalLayout_7.addWidget(self.browseButton_4)
        self.gridLayout.addLayout(self.verticalLayout_7, 4, 4, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.startNM_3 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.startNM_3.setDecimals(0)
        self.startNM_3.setMinimum(360.0)
        self.startNM_3.setMaximum(1800.0)
        self.startNM_3.setObjectName("startNM_3")
        self.horizontalLayout_7.addWidget(self.startNM_3)
        self.line_32 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_32.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.horizontalLayout_7.addWidget(self.line_32)
        self.stopNM_3 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.stopNM_3.setDecimals(0)
        self.stopNM_3.setMinimum(360.0)
        self.stopNM_3.setMaximum(1800.0)
        self.stopNM_3.setProperty("value", 1800.0)
        self.stopNM_3.setObjectName("stopNM_3")
        self.horizontalLayout_7.addWidget(self.stopNM_3)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.line_42 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_42.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_42.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_42.setObjectName("line_42")
        self.verticalLayout_8.addWidget(self.line_42)
        self.calculateButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.calculateButton_3.setFont(font)
        self.calculateButton_3.setObjectName("calculateButton_3")
        self.verticalLayout_8.addWidget(self.calculateButton_3)
        self.exportButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exportButton_3.setFont(font)
        self.exportButton_3.setObjectName("exportButton_3")
        self.verticalLayout_8.addWidget(self.exportButton_3)
        self.gridLayout_3.addLayout(self.verticalLayout_8, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 7, 7, 1, 1)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.textBox_8 = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textBox_8.setObjectName("textBox_8")
        self.verticalLayout_14.addWidget(self.textBox_8)
        self.browseButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.browseButton_8.setFont(font)
        self.browseButton_8.setObjectName("browseButton_8")
        self.verticalLayout_14.addWidget(self.browseButton_8)
        self.gridLayout.addLayout(self.verticalLayout_14, 10, 4, 1, 1)
        self.line_30 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_30.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.gridLayout.addWidget(self.line_30, 14, 0, 1, 1)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.textBox_9 = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textBox_9.setObjectName("textBox_9")
        self.verticalLayout_16.addWidget(self.textBox_9)
        self.browseButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.browseButton_9.setFont(font)
        self.browseButton_9.setObjectName("browseButton_9")
        self.verticalLayout_16.addWidget(self.browseButton_9)
        self.gridLayout.addLayout(self.verticalLayout_16, 13, 2, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.textBox_7 = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textBox_7.setObjectName("textBox_7")
        self.verticalLayout_12.addWidget(self.textBox_7)
        self.browseButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.browseButton_7.setFont(font)
        self.browseButton_7.setObjectName("browseButton_7")
        self.verticalLayout_12.addWidget(self.browseButton_7)
        self.gridLayout.addLayout(self.verticalLayout_12, 10, 2, 1, 1)
        self.line_36 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_36.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_36.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_36.setObjectName("line_36")
        self.gridLayout.addWidget(self.line_36, 14, 4, 1, 1)
        self.line_38 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_38.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_38.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_38.setObjectName("line_38")
        self.gridLayout.addWidget(self.line_38, 14, 7, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.stop_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stop_1.setFont(font)
        self.stop_1.setObjectName("stop_1")
        self.horizontalLayout_4.addWidget(self.stop_1)
        self.line_64 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_64.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_64.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_64.setObjectName("line_64")
        self.horizontalLayout_4.addWidget(self.line_64)
        self.start_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.start_1.setFont(font)
        self.start_1.setObjectName("start_1")
        self.horizontalLayout_4.addWidget(self.start_1)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 7, 1, 1)
        self.line_34 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_34.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_34.setObjectName("line_34")
        self.gridLayout.addWidget(self.line_34, 14, 2, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.textBox_3 = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textBox_3.setObjectName("textBox_3")
        self.verticalLayout_6.addWidget(self.textBox_3)
        self.browseButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.browseButton_3.setFont(font)
        self.browseButton_3.setObjectName("browseButton_3")
        self.verticalLayout_6.addWidget(self.browseButton_3)
        self.gridLayout.addLayout(self.verticalLayout_6, 4, 2, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.textBox_6 = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textBox_6.setObjectName("textBox_6")
        self.verticalLayout_10.addWidget(self.textBox_6)
        self.browseButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.browseButton_6.setFont(font)
        self.browseButton_6.setObjectName("browseButton_6")
        self.verticalLayout_10.addWidget(self.browseButton_6)
        self.gridLayout.addLayout(self.verticalLayout_10, 7, 4, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.textBox_5 = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textBox_5.setObjectName("textBox_5")
        self.verticalLayout_9.addWidget(self.textBox_5)
        self.browseButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.browseButton_5.setFont(font)
        self.browseButton_5.setObjectName("browseButton_5")
        self.verticalLayout_9.addWidget(self.browseButton_5)
        self.gridLayout.addLayout(self.verticalLayout_9, 7, 2, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.startNM_4 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.startNM_4.setDecimals(0)
        self.startNM_4.setMinimum(360.0)
        self.startNM_4.setMaximum(1800.0)
        self.startNM_4.setObjectName("startNM_4")
        self.horizontalLayout_9.addWidget(self.startNM_4)
        self.line_44 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_44.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_44.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_44.setObjectName("line_44")
        self.horizontalLayout_9.addWidget(self.line_44)
        self.stopNM_4 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.stopNM_4.setDecimals(0)
        self.stopNM_4.setMinimum(360.0)
        self.stopNM_4.setMaximum(1800.0)
        self.stopNM_4.setProperty("value", 1800.0)
        self.stopNM_4.setObjectName("stopNM_4")
        self.horizontalLayout_9.addWidget(self.stopNM_4)
        self.gridLayout_5.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.line_61 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_61.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_61.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_61.setObjectName("line_61")
        self.verticalLayout_13.addWidget(self.line_61)
        self.calculateButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.calculateButton_4.setFont(font)
        self.calculateButton_4.setObjectName("calculateButton_4")
        self.verticalLayout_13.addWidget(self.calculateButton_4)
        self.exportButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exportButton_4.setFont(font)
        self.exportButton_4.setObjectName("exportButton_4")
        self.verticalLayout_13.addWidget(self.exportButton_4)
        self.gridLayout_5.addLayout(self.verticalLayout_13, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 10, 7, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.startNM_1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.startNM_1.setDecimals(0)
        self.startNM_1.setMinimum(360.0)
        self.startNM_1.setMaximum(1800.0)
        self.startNM_1.setObjectName("startNM_1")
        self.horizontalLayout_8.addWidget(self.startNM_1)
        self.line_63 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_63.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_63.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_63.setObjectName("line_63")
        self.horizontalLayout_8.addWidget(self.line_63)
        self.stopNM_1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.stopNM_1.setDecimals(0)
        self.stopNM_1.setMinimum(360.0)
        self.stopNM_1.setMaximum(1800.0)
        self.stopNM_1.setProperty("value", 1800.0)
        self.stopNM_1.setObjectName("stopNM_1")
        self.horizontalLayout_8.addWidget(self.stopNM_1)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.line_66 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_66.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_66.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_66.setObjectName("line_66")
        self.verticalLayout_18.addWidget(self.line_66)
        self.calculateButton_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.calculateButton_1.setFont(font)
        self.calculateButton_1.setObjectName("calculateButton_1")
        self.verticalLayout_18.addWidget(self.calculateButton_1)
        self.exportButton_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exportButton_1.setFont(font)
        self.exportButton_1.setObjectName("exportButton_1")
        self.verticalLayout_18.addWidget(self.exportButton_1)
        self.gridLayout_4.addLayout(self.verticalLayout_18, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 2, 7, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.startNM_5 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.startNM_5.setDecimals(0)
        self.startNM_5.setMinimum(360.0)
        self.startNM_5.setMaximum(1800.0)
        self.startNM_5.setObjectName("startNM_5")
        self.horizontalLayout_10.addWidget(self.startNM_5)
        self.line_46 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_46.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_46.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_46.setObjectName("line_46")
        self.horizontalLayout_10.addWidget(self.line_46)
        self.stopNM_5 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.stopNM_5.setDecimals(0)
        self.stopNM_5.setMinimum(360.0)
        self.stopNM_5.setMaximum(1800.0)
        self.stopNM_5.setProperty("value", 1800.0)
        self.stopNM_5.setObjectName("stopNM_5")
        self.horizontalLayout_10.addWidget(self.stopNM_5)
        self.gridLayout_9.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.line_67 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_67.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_67.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_67.setObjectName("line_67")
        self.verticalLayout_15.addWidget(self.line_67)
        self.calculateButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.calculateButton_5.setFont(font)
        self.calculateButton_5.setObjectName("calculateButton_5")
        self.verticalLayout_15.addWidget(self.calculateButton_5)
        self.exportButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exportButton_5.setFont(font)
        self.exportButton_5.setObjectName("exportButton_5")
        self.verticalLayout_15.addWidget(self.exportButton_5)
        self.gridLayout_9.addLayout(self.verticalLayout_15, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_9, 13, 7, 1, 1)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.textBox_10 = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textBox_10.setObjectName("textBox_10")
        self.verticalLayout_17.addWidget(self.textBox_10)
        self.browseButton_10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.browseButton_10.setFont(font)
        self.browseButton_10.setObjectName("browseButton_10")
        self.verticalLayout_17.addWidget(self.browseButton_10)
        self.gridLayout.addLayout(self.verticalLayout_17, 13, 4, 1, 1)
        self.line_25 = QtWidgets.QFrame(self.centralwidget)
        self.line_25.setGeometry(QtCore.QRect(30, 910, 991, 20))
        self.line_25.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.line_26 = QtWidgets.QFrame(self.centralwidget)
        self.line_26.setGeometry(QtCore.QRect(20, 29, 20, 891))
        self.line_26.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.line_27 = QtWidgets.QFrame(self.centralwidget)
        self.line_27.setGeometry(QtCore.QRect(30, 20, 991, 16))
        self.line_27.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.line_28 = QtWidgets.QFrame(self.centralwidget)
        self.line_28.setGeometry(QtCore.QRect(1010, 30, 20, 891))
        self.line_28.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 820, 961, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.clearButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(False)
        self.clearButton.setFont(font)
        self.clearButton.setObjectName("clearButton")
        self.verticalLayout_2.addWidget(self.clearButton)
        self.exportButton_All = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(False)
        self.exportButton_All.setFont(font)
        self.exportButton_All.setObjectName("exportButton_All")
        self.verticalLayout_2.addWidget(self.exportButton_All)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1045, 25))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.browseButton_2.setText(_translate("MainWindow", "Select"))
        self.label_3.setText(_translate("MainWindow", "Range 3 :      "))
        self.label_2.setText(_translate("MainWindow", "Range 2 :      "))
        self.label_4.setText(_translate("MainWindow", "Range 5 :      "))
        self.label_5.setText(_translate("MainWindow", "Range 4 :      "))
        self.label.setText(_translate("MainWindow", "Range 1 :     "))
        self.label_7.setText(_translate("MainWindow", "Data File : "))
        self.label_6.setText(_translate("MainWindow", "Reference File : "))
        self.browseButton_1.setText(_translate("MainWindow", "Select"))
        self.calculateButton_2.setText(_translate("MainWindow", "Calculate EQE"))
        self.exportButton_2.setText(_translate("MainWindow", "Export Data "))
        self.browseButton_4.setText(_translate("MainWindow", "Select"))
        self.calculateButton_3.setText(_translate("MainWindow", "Calculate EQE"))
        self.exportButton_3.setText(_translate("MainWindow", "Export Data "))
        self.browseButton_8.setText(_translate("MainWindow", "Select"))
        self.browseButton_9.setText(_translate("MainWindow", "Select"))
        self.browseButton_7.setText(_translate("MainWindow", "Select"))
        self.stop_1.setText(_translate("MainWindow", "Stop [nm]     "))
        self.start_1.setText(_translate("MainWindow", "Start [nm]     "))
        self.browseButton_3.setText(_translate("MainWindow", "Select"))
        self.browseButton_6.setText(_translate("MainWindow", "Select"))
        self.browseButton_5.setText(_translate("MainWindow", "Select"))
        self.calculateButton_4.setText(_translate("MainWindow", "Calculate EQE"))
        self.exportButton_4.setText(_translate("MainWindow", "Export Data "))
        self.calculateButton_1.setText(_translate("MainWindow", "Calculate EQE"))
        self.exportButton_1.setText(_translate("MainWindow", "Export Data "))
        self.calculateButton_5.setText(_translate("MainWindow", "Calculate EQE"))
        self.exportButton_5.setText(_translate("MainWindow", "Export Data "))
        self.browseButton_10.setText(_translate("MainWindow", "Select"))
        self.clearButton.setText(_translate("MainWindow", "Clear Plot"))
        self.exportButton_All.setText(_translate("MainWindow", "Export All Data"))
        self.menu.setTitle(_translate("MainWindow", "sEQE Control Software"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

